// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIlcDdaobVU2AF_hR80KULxx8GqM8IuT0',
    appId: '1:607480746612:web:fd62891f24dafccd907721',
    messagingSenderId: '607480746612',
    projectId: 'campana-vacunacion-2026',
    authDomain: 'campana-vacunacion-2026.firebaseapp.com',
    storageBucket: 'campana-vacunacion-2026.firebasestorage.app',
    measurementId: 'G-ZGLTLC8Y4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa5cTccstSh-CgaafmTUbl2uz1HoyvJnM',
    appId: '1:607480746612:android:e5764f84f7c8fdb1907721',
    messagingSenderId: '607480746612',
    projectId: 'campana-vacunacion-2026',
    storageBucket: 'campana-vacunacion-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfPkBQWy38tGg6lxT373GMDiQoqvhd0zs',
    appId: '1:607480746612:ios:83e5d9203aa8e6da907721',
    messagingSenderId: '607480746612',
    projectId: 'campana-vacunacion-2026',
    storageBucket: 'campana-vacunacion-2026.firebasestorage.app',
    iosBundleId: 'com.vacunacion.app.campanaVacunacion2026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfPkBQWy38tGg6lxT373GMDiQoqvhd0zs',
    appId: '1:607480746612:ios:83e5d9203aa8e6da907721',
    messagingSenderId: '607480746612',
    projectId: 'campana-vacunacion-2026',
    storageBucket: 'campana-vacunacion-2026.firebasestorage.app',
    iosBundleId: 'com.vacunacion.app.campanaVacunacion2026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIlcDdaobVU2AF_hR80KULxx8GqM8IuT0',
    appId: '1:607480746612:web:af23698f0286c18d907721',
    messagingSenderId: '607480746612',
    projectId: 'campana-vacunacion-2026',
    authDomain: 'campana-vacunacion-2026.firebaseapp.com',
    storageBucket: 'campana-vacunacion-2026.firebasestorage.app',
    measurementId: 'G-95EHH52K3R',
  );
}
